In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
file_path = "./reviews.csv"

df = pd.read_csv(file_path)
df

,user_id,product_id,score,comment,createdAt,updatedAt,id
0,7,4,3,Chất lượng của sản phẩm vượt xa mong đợi của t...,2024-01-02 05:42:48.983148,2024-05-01 03:19:13.79401,2113415
1,53,31,4,Đó là một lựa chọn tuyệt vời cho thú cưng của ...,2024-03-17 11:32:27.075948,2024-05-01 03:19:13.79401,2113416
2,11,14,3,Sản phẩm này thực sự là một điều cần thiết cho...,2024-02-24 04:17:19.933548,2024-05-01 03:19:13.79401,2113417
3,49,14,3,Tôi đã giới thiệu sản phẩm này cho nhiều bạn b...,2024-02-10 05:12:59.725548,2024-05-01 03:19:13.79401,2113418
4,8,9,5,Tôi đã dành rất nhiều thời gian để tìm kiếm sả...,2024-02-15 01:31:12.656748,2024-05-01 03:19:13.79401,2113419
...,...,...,...,...,...,...,...
134,1,11,4,"Thú cưng của tôi rất thích ăn sản phẩm này, ăn...",2024-03-21 20:04:37.741548,2024-05-01 03:24:51.514933,2113482
135,62,25,5,rất hài lòng về sản phẩm!,2024-05-01 18:08:13.689,2024-05-01 18:08:13.689,2113501
136,62,42,5,rất tốt!,2024-05-03 15:43:16.835,2024-05-03 15:43:16.835,2113505
137,63,5,3,Sản phẩm dùng tốt nhưng giá tiền còn khá cao,2024-05-07 18:07:18.37,2024-05-07 18:07:18.37,2113509
138,49,86,5,Tôi đã dành rất nhiều thời gian để tìm kiếm mộ...,2024-03-26 06:58:25.501548,2024-05-08 16:33:20.99705,2113446

In [2]:
df = df[['user_id', 'product_id', 'score']]
df

     user_id  product_id  score
0          7           4      3
1         53          31      4
2         11          14      3
3         49          14      3
4          8           9      5
..       ...         ...    ...
134        1          11      4
135       62          25      5
136       62          42      5
137       63           5      3
138       49          86      5

[139 rows x 3 columns]

In [3]:
import pandas as pd

pivot_df = df.pivot_table(index='user_id', columns='product_id', values='score', fill_value=0)
print(pivot_df)

product_id  1    2    3    4    5    6    7    8    9    10   ...  94   95   \
user_id                                                       ...
1             0    0    0    0    0    0    0    0    0  0.0  ...    0    0
2             0    0    5    0    0    0    5    0    0  0.0  ...    0    0
3             0    0    0    0    0    0    0    0    0  0.0  ...    0    0
4             0    0    0    0    0    0    0    0    0  0.0  ...    0    0
6             0    0    0    0    0    0    0    0    0  0.0  ...    0    0
7             0    0    0    3    0    0    0    0    0  0.0  ...    0    0
8             0    0    0    0    0    0    0    0    5  0.0  ...    0    0
9             0    0    0    0    0    0    0    0    0  3.0  ...    0    0
10            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
11            0    0    0    0    0    0    0    5    0  0.0  ...    0    0
12            0    0    0    0    5    0    0    0    0  5.0  ...    0    0
13            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
14            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
15            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
16            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
17            4    0    0    4    0    0    0    0    0  0.0  ...    0    5
19            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
20            0    0    0    0    0    0    0    0    0  0.0  ...    5    0
21            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
22            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
23            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
24            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
26            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
27            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
28            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
29            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
30            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
31            0    0    0    0    0    0    0    0    0  3.0  ...    0    0
32            0    0    0    0    0    0    0    0    0  3.5  ...    0    0
33            0    0    0    0    0    4    0    0    0  0.0  ...    0    0
34            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
35            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
36            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
37            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
38            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
39            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
40            0    0    0    0    0    0    0    3    0  0.0  ...    0    0
41            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
42            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
43            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
44            0    3    0    0    0    0    0    0    0  0.0  ...    0    0
45            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
46            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
47            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
49            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
50            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
51            0    0    5    0    0    0    0    0    0  0.0  ...    0    0
52            0    0    0    0    0    0    0    0    3  0.0  ...    0    0
53            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
54            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
55            0    0    0    0    0    0    0    0    0  0.0  ...    0    0
62            0    4    0    0    0    0    0    0    0  0.0  ...    0    0
63            0    0    0    0    3    0    0    0    0  0.0  ...    0    0
64            0    0    0    0    0    0    0    0    0  0.0  ...    0    0

product_id  97   99   100  101  102  105  106  107
user_id
1             0    0    0    0    0    0    0    0
2             0    0    0    0    0    0    0    0
3             0    0    0    0    0    0    0    0
4             0    0    0    0    0    0    0    0
6             0    0    0    0    0    0    0    0
7             0    0    0    0    0    0    0    0
8             0    0    0    0    0    0    0    0
9             0    0    0    0    0    0    0    0
10            0    0    0    0    0    0    0    0
11            0    0    0    0    0    0    0    0
12            0    0    0    0    0    0    0    0
13            0    0    0    0    0    0    0    0
14            0    0    0    0    0    0    0    0
15            0    0    0    0    0    0    0    0
16            3    0    0    0    0    0    0    0
17            0    0    0    0    0    0    5    0
19            0    0    0    0    0    0    0    0
20            0    0    0    0    0    0    0    0
21            0    0    0    0    0    0    0    0
22            0    0    0    0    0    0    0    0
23            0    0    0    0    0    0    0    0
24            0    0    0    0    0    0    0    0
26            0    0    0    0    0    4    0    0
27            0    0    0    0    0    0    0    0
28            0    0    0    0    0    0    0    0
29            0    0    0    0    0    0    0    0
30            0    0    0    0    0    0    0    0
31            0    0    0    0    0    0    0    0
32            0    0    0    0    0    0    0    0
33            0    0    0    0    0    0    0    0
34            0    0    0    0    0    0    0    0
35            0    0    0    0    0    0    0    0
36            0    0    4    0    0    0    0    0
37            0    0    0    0    0    0    0    0
38            0    0    0    0    0    0    0    0
39            0    0    0    0    0    0    0    0
40            0    0    0    0    0    0    0    0
41            0    0    0    0    5    0    0    0
42            0    0    0    0    0    0    0    5
43            0    0    0    0    0    0    0    0
44            0    0    0    0    0    0    0    0
45            0    0    0    0    0    0    0    0
46            0    0    0    0    0    0    0    0
47            0    0    0    0    0    0    0    0
49            0    0    0    0    0    0    0    0
50            0    0    0    0    0    0    0    0
51            0    0    4    0    0    0    0    0
52            0    0    0    5    0    0    0    0
53            0    0    0    0    0    0    0    0
54            0    0    0    0    0    0    0    0
55            0    0    0    0    0    0    0    0
62            0    0    0    0    0    0    0    0
63            0    0    0    0    0    0    0    0
64            0    4    0    0    0    0    0    0

[54 rows x 76 columns]

In [4]:
item = list(pivot_df.columns)
user = list(pivot_df.index)

In [5]:
import numpy as np
import pandas as pd

def random_fill(x):
    if pd.isnull(x):
        return np.random.randint(0, 6)  # Trả về một số ngẫu nhiên từ 0 đến 5 nếu giá trị là NaN
    else:
        return np.random.randint(0, 6)  # Trả về một số ngẫu nhiên từ 0 đến 5 nếu giá trị là NaN


data_matrix = pivot_df.applymap(random_fill).values

print(data_matrix)

[[4 5 1 ... 2 4 5]
 [2 5 3 ... 1 2 4]
 [0 5 3 ... 5 1 0]
 ...
 [4 4 4 ... 3 5 5]
 [0 0 3 ... 0 3 0]
 [2 0 3 ... 1 5 4]]

In [6]:
data_matrix

array([[4, 5, 1, ..., 2, 4, 5],
       [2, 5, 3, ..., 1, 2, 4],
       [0, 5, 3, ..., 5, 1, 0],
       ...,
       [4, 4, 4, ..., 3, 5, 5],
       [0, 0, 3, ..., 0, 3, 0],
       [2, 0, 3, ..., 1, 5, 4]], dtype=int64)

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

Sim = cosine_similarity(data_matrix,data_matrix)
Sim = np.round(Sim, decimals = 2)
Sim

array([[1.  , 0.68, 0.61, ..., 0.6 , 0.64, 0.61],
       [0.68, 1.  , 0.72, ..., 0.73, 0.69, 0.72],
       [0.61, 0.72, 1.  , ..., 0.6 , 0.66, 0.72],
       ...,
       [0.6 , 0.73, 0.6 , ..., 1.  , 0.69, 0.71],
       [0.64, 0.69, 0.66, ..., 0.69, 1.  , 0.72],
       [0.61, 0.72, 0.72, ..., 0.71, 0.72, 1.  ]])

In [8]:
pd.DataFrame(Sim, columns=user, index=user)

,1,2,3,4,6,7,8,9,10,11,...,49,50,51,52,53,54,55,62,63,64
1,1.00,0.68,0.61,0.69,0.70,0.71,0.67,0.70,0.65,0.71,...,0.65,0.62,0.63,0.70,0.68,0.66,0.69,0.60,0.64,0.61
2,0.68,1.00,0.72,0.71,0.66,0.70,0.69,0.73,0.69,0.69,...,0.62,0.65,0.64,0.68,0.69,0.71,0.68,0.73,0.69,0.72
3,0.61,0.72,1.00,0.68,0.67,0.67,0.67,0.74,0.64,0.74,...,0.64,0.64,0.72,0.61,0.69,0.73,0.64,0.60,0.66,0.72
4,0.69,0.71,0.68,1.00,0.68,0.68,0.70,0.77,0.67,0.77,...,0.64,0.72,0.77,0.66,0.73,0.69,0.73,0.72,0.70,0.69
6,0.70,0.66,0.67,0.68,1.00,0.70,0.71,0.67,0.70,0.64,...,0.65,0.65,0.67,0.67,0.71,0.58,0.71,0.62,0.72,0.73
7,0.71,0.70,0.67,0.68,0.70,1.00,0.74,0.75,0.68,0.75,...,0.71,0.57,0.65,0.73,0.68,0.69,0.71,0.73,0.67,0.76
8,0.67,0.69,0.67,0.70,0.71,0.74,1.00,0.71,0.63,0.70,...,0.66,0.64,0.69,0.65,0.64,0.70,0.78,0.70,0.69,0.71
9,0.70,0.73,0.74,0.77,0.67,0.75,0.71,1.00,0.63,0.83,...,0.60,0.61,0.74,0.67,0.69,0.74,0.69,0.68,0.65,0.72
10,0.65,0.69,0.64,0.67,0.70,0.68,0.63,0.63,1.00,0.68,...,0.61,0.60,0.74,0.61,0.73,0.64,0.70,0.60,0.69,0.64
11,0.71,0.69,0.74,0.77,0.64,0.75,0.70,0.83,0.68,1.00,...,0.67,0.59,0.76,0.69,0.75,0.73,0.71,0.66,0.66,0.67
12,0.67,0.71,0.75,0.67,0.70,0.69,0.71,0.72,0.67,0.77,...,0.65,0.71,0.73,0.66,0.71,0.75,0.71,0.66,0.73,0.73
13,0.70,0.78,0.72,0.77,0.71,0.73,0.71,0.72,0.66,0.75,...,0.74,0.64,0.71,0.70,0.74,0.72,0.66,0.68,0.74,0.74
14,0.67,0.64,0.60,0.64,0.64,0.75,0.64,0.68,0.64,0.67,...,0.64,0.67,0.62,0.66,0.68,0.65,0.70,0.70,0.70,0.62
15,0.66,0.74,0.74,0.64,0.70,0.68,0.64,0.67,0.67,0.67,...,0.67,0.68,0.68,0.64,0.72,0.70,0.67,0.62,0.67,0.71
16,0.66,0.68,0.68,0.77,0.71,0.68,0.68,0.81,0.63,0.73,...,0.62,0.66,0.76,0.67,0.66,0.72,0.76,0.71,0.69,0.69
17,0.64,0.71,0.73,0.74,0.57,0.65,0.65,0.70,0.63,0.70,...,0.67,0.66,0.70,0.64,0.64,0.68,0.66,0.71,0.59,0.64
19,0.61,0.74,0.70,0.73,0.65,0.67,0.71,0.70,0.68,0.67,...,0.62,0.74,0.75,0.65,0.69,0.75,0.68,0.73,0.69,0.69
20,0.61,0.68,0.68,0.70,0.71,0.72,0.73,0.70,0.63,0.66,...,0.67,0.60,0.66,0.66,0.68,0.65,0.72,0.70,0.68,0.69
21,0.64,0.66,0.67,0.65,0.63,0.63,0.66,0.65,0.63,0.66,...,0.70,0.61,0.67,0.68,0.65,0.64,0.69,0.60,0.65,0.67
22,0.67,0.72,0.72,0.70,0.62,0.66,0.65,0.71,0.70,0.74,...,0.64,0.64,0.70,0.67,0.73,0.75,0.67,0.63,0.70,0.65
23,0.68,0.65,0.67,0.71,0.67,0.70,0.70,0.70,0.59,0.68,...,0.63,0.75,0.71,0.67,0.71,0.67,0.70,0.67,0.66,0.66
24,0.62,0.59,0.61,0.66,0.57,0.66,0.67,0.66,0.58,0.72,...,0.63,0.58,0.70,0.71,0.65,0.70,0.67,0.65,0.65,0.60
26,0.62,0.65,0.68,0.65,0.67,0.64,0.72,0.68,0.62,0.65,...,0.66,0.63,0.63,0.70,0.73,0.65,0.71,0.69,0.73,0.71
27,0.58,0.71,0.69,0.64,0.63,0.65,0.66,0.68,0.72,0.71,...,0.64,0.64,0.70,0.62,0.72,0.67,0.70,0.68,0.65,0.68
28,0.64,0.75,0.61,0.70,0.61,0.70,0.65,0.65,0.65,0.65,...,0.65,0.62,0.64,0.67,0.69,0.65,0.68,0.75,0.71,0.67
29,0.67,0.72,0.71,0.76,0.67,0.71,0.68,0.79,0.63,0.71,...,0.63,0.67,0.66,0.64,0.68,0.74,0.67,0.68,0.66,0.71
30,0.65,0.70,0.64,0.71,0.65,0.70,0.67,0.73,0.65,0.72,...,0.68,0.61,0.69,0.68,0.70,0.69,0.72,0.69,0.70,0.68
31,0.56,0.68,0.58,0.66,0.70,0.68,0.68,0.69,0.69,0.63,...,0.62,0.62,0.69,0.66,0.67,0.63,0.70,0.68,0.60,0.63
32,0.66,0.68,0.74,0.68,0.64,0.63,0.67,0.70,0.70,0.72,...,0.68,0.66,0.76,0.67,0.74,0.61,0.70,0.62,0.70,0.63
33,0.67,0.69,0.70,0.69,0.63,0.66,0.67,0.73,0.70,0.72,...,0.64,0.58,0.75,0.66,0.70,0.75,0.66,0.67,0.71,0.69
34,0.65,0.66,0.60,0.64,0.56,0.67,0.68,0.72,0.60,0.72,...,0.60,0.54,0.65,0.69,0.64,0.64,0.58,0.70,0.60,0.58
35,0.69,0.70,0.64,0.76,0.67,0.67,0.73,0.72,0.68,0.67,...,0.68,0.73,0.73,0.76,0.67,0.69,0.73,0.75,0.74,0.73
36,0.69,0.69,0.56,0.74,0.66,0.68,0.79,0.72,0.67,0.72,...,0.70,0.66,0.77,0.72,0.65,0.64,0.75,0.67,0.67,0.64
37,0.66,0.72,0.73,0.74,0.70,0.69,0.69,0.78,0.63,0.74,...,0.72,0.68,0.73,0.61,0.71,0.71,0.73,0.65,0.66,0.69
38,0.70,0.68,0.71,0.68,0.71,0.70,0.69,0.69,0.58,0.73,...,0.64,0.62,0.73,0.68,0.61,0.61,0.67,0.62,0.63,0.70
39,0.67,0.65,0.71,0.73,0.73,0.71,0.68,0.72,0.66,0.76,...,0.67,0.65,0.80,0.68,0.65,0.64,0.73,0.70,0.67,0.68
40,0.69,0.76,0.64,0.71,0.67,0.71,0.72,0.67,0.74,0.71,...,0.68,0.67,0.75,0.72,0.70,0.67,0.74,0.69,0.70,0.70
41,0.68,0.68,0.60,0.73,0.59,0.66,0.72,0.67,0.62,0.73,...,0.66,0.65,0.67,0.56,0.73,0.66,0.72,0.69,0.69,0.65
42,0.69,0.68,0.67,0.71,0.66,0.76,0.67,0.76,0.62,0.74,...,0.68,0.62,0.72,0.70,0.65,0.71,0.67,0.63,0.66,0.65
43,0.66,0.66,0.59,0.70,0.60,0.65,0.70,0.69,0.66,0.69,...,0.67,0.60,0.69,0.63,0.70,0.62,0.72,0.67,0.74,0.66
44,0.66,0.64,0.67,0.67,0.72,0.68,0.70,0.64,0.70,0.70,...,0.71,0.73,0.69,0.63,0.72,0.62,0.73,0.70,0.66,0.67
45,0.73,0.64,0.66,0.68,0.75,0.71,0.68,0.66,0.69,0.70,...,0.65,0.63,0.74,0.65,0.71,0.63,0.68,0.71,0.62,0.71
46,0.62,0.69,0.59,0.68,0.66,0.72,0.68,0.67,0.63,0.73,...,0.61,0.67,0.68,0.73,0.73,0.73,0.69,0.73,0.76,0.69
47,0.61,0.67,0.68,0.71,0.62,0.63,0.65,0.71,0.59,0.78,...,0.58,0.67,0.74,0.58,0.73,0.70,0.65,0.66,0.67,0.69
49,0.65,0.62,0.64,0.64,0.65,0.71,0.66,0.60,0.61,0.67,...,1.00,0.61,0.68,0.68,0.67,0.64,0.64,0.66,0.65,0.65
50,0.62,0.65,0.64,0.72,0.65,0.57,0.64,0.61,0.60,0.59,...,0.61,1.00,0.70,0.62,0.66,0.67,0.62,0.69,0.70,0.64
51,0.63,0.64,0.72,0.77,0.67,0.65,0.69,0.74,0.74,0.76,...,0.68,0.70,1.00,0.65,0.69,0.71,0.71,0.69,0.68,0.71
52,0.70,0.68,0.61,0.66,0.67,0.73,0.65,0.67,0.61,0.69,...,0.68,0.62,0.65,1.00,0.66,0.73,0.66,0.72,0.72,0.65
53,0.68,0.69,0.69,0.73,0.71,0.68,0.64,0.69,0.73,0.75,...,0.67,0.66,0.69,0.66,1.00,0.67,0.70,0.70,0.78,0.74
54,0.66,0.71,0.73,0.69,0.58,0.69,0.70,0.74,0.64,0.73,...,0.64,0.67,0.71,0.73,0.67,1.00,0.71,0.68,0.68,0.73
55,0.69,0.68,0.64,0.73,0.71,0.71,0.78,0.69,0.70,0.71,...,0.64,0.62,0.71,0.66,0.70,0.71,1.00,0.65,0.73,0.71
62,0.60,0.73,0.60,0.72,0.62,0.73,0.70,0.68,0.60,0.66,...,0.66,0.69,0.69,0.72,0.70,0.68,0.65,1.00,0.69,0.71
63,0.64,0.69,0.66,0.70,0.72,0.67,0.69,0.65,0.69,0.66,...,0.65,0.70,0.68,0.72,0.78,0.68,0.73,0.69,1.00,0.72
64,0.61,0.72,0.72,0.69,0.73,0.76,0.71,0.72,0.64,0.67,...,0.65,0.64,0.71,0.65,0.74,0.73,0.71,0.71,0.72,1.00

In [9]:
def predict(A, u,i, k):
    user_rated_i = np.where(A[:,i] !=0)[0]
    sim = Sim[u, user_rated_i]
    a = (np.argsort(sim))[-k:]
    nearest_s =sim[a]
    rating = A[user_rated_i[a],i]
    r_bar = (rating*nearest_s).sum()/(np.abs(nearest_s).sum())
    return np.round(r_bar)

In [10]:
predict_matrix = data_matrix.copy()
for u in range(0, predict_matrix.shape[0]):
  for i in range(0, predict_matrix.shape[1]):
    if data_matrix[u,i] ==0:
      id = i
      predict_matrix[u,i] = predict(data_matrix,u,id, 25)
predict_matrix

array([[4, 5, 1, ..., 2, 4, 5],
       [2, 5, 3, ..., 1, 2, 4],
       [3, 5, 3, ..., 5, 1, 3],
       ...,
       [4, 4, 4, ..., 3, 5, 5],
       [3, 2, 3, ..., 3, 3, 3],
       [2, 3, 3, ..., 1, 5, 4]], dtype=int64)

In [11]:
import numpy as np

def predict_item_average(A, i):
    rated_items = A[:, i]
    rated_items = rated_items[rated_items != 0]
    if len(rated_items) == 0:
        return np.nan
    return np.mean(rated_items)

predicted_rating = predict_item_average(data_matrix, i)
print(predicted_rating)

3.0

In [12]:
predict_matrixItem = data_matrix.copy()
for u in range(0, predict_matrixItem.shape[0]):
  for i in range(0, predict_matrixItem.shape[1]):
    if data_matrix[u,i] ==0:
      id = i
      predict_matrixItem[u,i] = predict_item_average(data_matrix,id)
predict_matrixItem

array([[4, 5, 1, ..., 2, 4, 5],
       [2, 5, 3, ..., 1, 2, 4],
       [2, 5, 3, ..., 5, 1, 3],
       ...,
       [4, 4, 4, ..., 3, 5, 5],
       [2, 2, 3, ..., 2, 3, 3],
       [2, 2, 3, ..., 1, 5, 4]], dtype=int64)

In [13]:
from sklearn.metrics import mean_squared_error
import numpy as np
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(data_matrix, test_size=0.3, random_state=50)

def calculate_rmse_user_average(predicted_matrix, true_matrix):
    predicted_values = predicted_matrix[true_matrix != 0]
    true_values = true_matrix[true_matrix != 0]
    return np.sqrt(mean_squared_error(true_values, predicted_values))

# Tính dự đoán cho tất cả các mục trong tập kiểm thử
predicted_matrix = np.zeros_like(test_data)
for u in range(test_data.shape[0]):
    for i in range(test_data.shape[1]):
        if test_data[u, i] == 0:  # Chỉ dự đoán cho các mục chưa được đánh giá
            predicted_matrix[u, i] = predict(train_data, u, i, 25)  # Sử dụng hàm predict để dự đoán

# Tính toán RMSE
rmse = calculate_rmse_user_average(predicted_matrix, test_data)
print("RMSE User-KNNCF:", rmse)

RMSE User-KNNCF: 3.31096308463903

In [14]:
train_data2, test_data2 = train_test_split(data_matrix, test_size=0.3, random_state=42)

def calculate_rmse_item_average(predicted_matrix, true_matrix):
    predicted_values = predicted_matrix[true_matrix != 0]
    true_values = true_matrix[true_matrix != 0]
    return np.sqrt(mean_squared_error(true_values, predicted_values))

# Tính dự đoán trung bình cho mỗi mục trong tập kiểm thử
predicted_matrix_item_average = np.zeros_like(test_data2)
for i in range(test_data2.shape[1]):
    for u in range(test_data2.shape[0]):
        if test_data2[u, i] == 0:  # Chỉ dự đoán cho các mục chưa được đánh giá
            predicted_matrix_item_average[u, i] = predict_item_average(train_data2, i)  # Sử dụng hàm predict_item_average để dự đoán

# Tính toán RMSE
rmse_item_average = calculate_rmse_item_average(predicted_matrix_item_average, test_data2)
print("RMSE của Item Average:", rmse_item_average)

RMSE của Item Average: 3.273167231546827

In [15]:
import pandas as pd

# Tạo DataFrame chứa dữ liệu RMSE
rs = {
    "Method": ["User-KNNCF", "Item Average"],
    "RMSE": [rmse, rmse_item_average]
}

dfrs = pd.DataFrame(rs)

# In ra bảng so sánh
print(dfrs)

         Method      RMSE
0    User-KNNCF  3.335117
1  Item Average  3.273167

In [16]:
!pip install typer==0.12.3

Collecting typer==0.12.3
  Downloading typer-0.12.3-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.2/47.2 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer==0.12.3) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from typer==0.12.3) (4.11.0)
Collecting shellingham>=1.3.0 (from typer==0.12.3)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer==0.12.3) (13.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer==0.12.3) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer==0.12.3) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer==0.12.3) (0.1.2)
Installing collected packages: shellingham, typer
  Attempting uninstall: typer
    Found existing installation: typer 0.9.4
    Uninstalling typer-0.9.4:
      Successfully uninstalled typer-0.9.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy 3.7.4 requires typer<0.10.0,>=0.3.0, but you have typer 0.12.3 which is incompatible.
weasel 0.3.4 requires typer<0.10.0,>=0.3.0, but you have typer 0.12.3 which is incompatible.
Successfully installed shellingham-1.5.4 typer-0.12.3

In [18]:
!pip install fastapi uvicorn

Collecting fastapi
  Downloading fastapi-0.111.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 2.2 MB/s eta 0:00:00
Collecting uvicorn
  Downloading uvicorn-0.29.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 6.3 MB/s eta 0:00:00
Collecting starlette<0.38.0,>=0.37.2 (from fastapi)
  Downloading starlette-0.37.2-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 7.2 MB/s eta 0:00:00
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from fastapi) (2.7.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from fastapi) (4.11.0)
Collecting fastapi-cli>=0.0.2 (from fastapi)
  Downloading fastapi_cli-0.0.3-py3-none-any.whl (9.2 kB)
Collecting httpx>=0.23.0 (from fastapi)
  Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 7.3 MB/s eta 0:00:00
Requirement already satisfied: jinja2>=2.11.2 in /usr/local/lib/python3.10/dist-packages (from fastapi) (3.1.4)
Collecting python-multipart>=0.0.7 (from fastapi)
  Downloading python_multipart-0.0.9-py3-none-any.whl (22 kB)
Collecting ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1 (from fastapi)
  Downloading ujson-5.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB 6.5 MB/s eta 0:00:00
Collecting orjson>=3.2.1 (from fastapi)
  Downloading orjson-3.10.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.5/142.5 kB 5.8 MB/s eta 0:00:00
Collecting email_validator>=2.0.0 (from fastapi)
  Downloading email_validator-2.1.1-py3-none-any.whl (30 kB)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.10/dist-packages (from uvicorn) (8.1.7)
Collecting h11>=0.8 (from uvicorn)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.7 MB/s eta 0:00:00
Collecting dnspython>=2.0.0 (from email_validator>=2.0.0->fastapi)
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 10.4 MB/s eta 0:00:00
Requirement already satisfied: idna>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from email_validator>=2.0.0->fastapi) (3.7)
Requirement already satisfied: typer>=0.12.3 in /usr/local/lib/python3.10/dist-packages (from fastapi-cli>=0.0.2->fastapi) (0.12.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.23.0->fastapi) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.23.0->fastapi) (2024.2.2)
Collecting httpcore==1.* (from httpx>=0.23.0->fastapi)
  Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 8.0 MB/s eta 0:00:00
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.23.0->fastapi) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.11.2->fastapi) (2.1.5)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.2 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.18.2)
Collecting httptools>=0.5.0 (from uvicorn)
  Downloading httptools-0.6.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.4/341.4 kB 14.0 MB/s eta 0:00:00
Collecting python-dotenv>=0.13 (from uvicorn)
  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from uvicorn) (6.0.1)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn)
  Downloading uvloop-0.19.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 17.7 MB/s eta 0:00:00
Collecting watchfiles>=0.13 (from uvicorn)
  Downloading watchfiles-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 27.4 MB/s eta 0:00:00
Collecting websockets>=10.4 (from uvicorn)
  Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 10.0 MB/s eta 0:00:00
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx>=0.23.0->fastapi) (1.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi) (13.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi) (0.1.2)
Installing collected packages: websockets, uvloop, ujson, python-multipart, python-dotenv, orjson, httptools, h11, dnspython, watchfiles, uvicorn, starlette, httpcore, email_validator, httpx, fastapi-cli, fastapi
Successfully installed dnspython-2.6.1 email_validator-2.1.1 fastapi-0.111.0 fastapi-cli-0.0.3 h11-0.14.0 httpcore-1.0.5 httptools-0.6.1 httpx-0.27.0 orjson-3.10.3 python-dotenv-1.0.1 python-multipart-0.0.9 starlette-0.37.2 ujson-5.9.0 uvicorn-0.29.0 uvloop-0.19.0 watchfiles-0.21.0 websockets-12.0

In [17]:
pip install pyngrok

Collecting pyngrok
  Downloading pyngrok-7.1.6-py3-none-any.whl (22 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.10/dist-packages (from pyngrok) (6.0.1)
Installing collected packages: pyngrok
Successfully installed pyngrok-7.1.6

In [ ]:
from fastapi import FastAPI
import uvicorn
from pyngrok import ngrok
app = FastAPI()

@app.get("/")
async def read_root():
    return {"message": "Hello World"}

@app.post("/predict")
async def predict(data: dict):
    # Xử lý dữ liệu đầu vào
    # Chạy hàm predict với dữ liệu đã nhận
    result = {}  # Kết quả từ hàm predict
    return result

if __name__ == "__main__":


    # Khởi động server FastAPI
    uvicorn.run(app, host="127.0.0.1", port=8000)

    # Kết nối với ngrok để tạo một URL public cho FastAPI
    public_url = ngrok.connect(port="8000")
    print("Public URL:", public_url)